name: myweb
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: any
  transparent_image: ^1.0.0

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: "fonts/MaterialIcons-Regular.ttf"
          weight: 700
    
  assets:
    - images/Mystery.png
    - images/error.jpg
    - images/d290f1ee-6c54-4b01-90e6-d701748f0851.png
    - images/wheel.png
