name: myweb
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase: any
  flutter:
    sdk: flutter
  http: any
  transparent_image: ^1.0.0
  animator: any
  carousel_slider: ^1.3.0
  animated_background: ^1.0.5
  json_to_form: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: web/assets/fonts/RobotoMono-Regular.ttf
        - asset: web/assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: web/assets/fonts/OpenSans-Regular.ttf
        - asset: web/assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: "web/assets/fonts/MaterialIcons-Regular.ttf"
          weight: 700
    
  assets:
    - web/assets/images/Mystery.png
    - web/assets/images/error.jpg
    - web/assets/images/wheel.png
